### ISSUE TITLE
Improvements to 2FA workflow

### ISSUE THREAD

**Issue by ei8fdb** [sprblm/simsec-hypha-admgmt#1]
2FA authentication has been enforced on OTF's hypha instance. 2FA is implemented using [Django Two Factor Authentication](https://github.com/jazzband/django-two-factor-auth).

We've been tasked to make improvements to the 2FA workflow.

# Issue 2828
Things to do here:
- [x] investigate designs
- [x] get feedback from otf
- [ ] get feedback from hypha adopters?
- [x] get decision on what design flow to go with
- [ ] test flow designs with hypha adopters
- [x] finalise designs

# Issue 2821
Things to do here:

- [x] investigate different ways for staff user to disable a users 2FA
- [x] get [feedback from otf](https://app.zenhub.com/workspaces/otf-ux-design-work-62160ff31c39900014236c2f/issues/hyphaapp/hypha/2821#issuecomment-1112071731)
- [ ] get feedback from hypha adopters?
- [ ] get decision on what disable flow to go with
- [ ] test flow designs with hypha adopters
- [ ] finalise designs

**Comment by ei8fdb** [comment]
For #2828, decision was testing flow designs with hypha adopters was not required.
