### ISSUE TITLE
Implement compliance and contracting workflow

### ISSUE THREAD

**Issue by ei8fdb** [sprblm/simsec-hypha-admgmt#4]

**Comment by ei8fdb** [comment]
[Laura and Donny have made comments](https://docs.google.com/document/d/1R4WbdUtpBcvNoa-qBbnsjq6RtXv0Z0Le-Ufqd1LW_MU/edit) on the compliance and contracting workflow.

Bernard needs to review them.

Di is asking for a meeting to discuss them.

**Comment by ei8fdb** [comment]
We're waiting for the following from OTF:

- [ ] [finalised](https://docs.google.com/document/d/1R4WbdUtpBcvNoa-qBbnsjq6RtXv0Z0Le-Ufqd1LW_MU/edit?disco=AAAAYjX17IQ) Project Application Form
- [ ] [decision](https://docs.google.com/document/d/1R4WbdUtpBcvNoa-qBbnsjq6RtXv0Z0Le-Ufqd1LW_MU/edit?disco=AAAAYjX17IE) to make PAF start/end date fields editable, **or** to put estimated/proposed in front of start/end date. 
- [ ] [final decision](https://docs.google.com/document/d/1R4WbdUtpBcvNoa-qBbnsjq6RtXv0Z0Le-Ufqd1LW_MU/edit?disco=AAAAYjX17Lk) if sending contract to contractor should go through webapp or not  
- [ ] clarification on the contract signing process
- [ ] [decision](https://docs.google.com/document/d/1R4WbdUtpBcvNoa-qBbnsjq6RtXv0Z0Le-Ufqd1LW_MU/edit?disco=AAAAYjX17Ls) on changing "review on behlf of" to "reviewing PAF for..."
- [ ] [decision](https://docs.google.com/document/d/1R4WbdUtpBcvNoa-qBbnsjq6RtXv0Z0Le-Ufqd1LW_MU/edit?disco=AAAAYjX17Lw) on if they want who clicked what kinda review to be recorded

**Comment by ei8fdb** [comment]
Having meeting with Laura, Donny today about their comments and next steps.
